spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javapro
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 9m!3PIk+
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    generate-ddl: false
  liquibase:
    url: jdbc:postgresql://localhost:5432/javapro
    user: postgres
    password: 9m!3PIk+
    enabled: true
    contexts: dev
    change-log: classpath:db.changelog/db.changelog-master.yml
  mail:
    address: http://localhost:8080
    host: smtp.gmail.com
    port: 587
    username: devSocialLine@gmail.com
    password: ntcngjxnf12
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8
server:
  port: 8086
#logging:
#  config: classpath:log4j2-spring-dev.xml
# У каждого на своем компе будет своя переменная. Меняйте раскоменчивайте нужную, а не нужные в коммент
# под MacOS
#javapro.storagepath: "C:/Users/maksi/Desktop/diplom project/storage"
# под win каждый пишет свою строчку, в зависимости от нахождения папки с хранилищем.
#javapro.storagepath: C:/Users/maksi/Desktop/SocialNetworkStorage
javapro.storagepath.baseurl: http://31.40.251.201:8086
javapro.storagepath: C:/Users/maksi/Desktop/SocialNetworkStorage/